### ISSUE TITLE
How to use Antiforgery with a JS client on separate subdomain?

### ISSUE THREAD

**Issue by kavinsky-** [aspnet/Antiforgery#130] opened 2017-03-12 23:12 UTC
Hi Everyone 

I have an ASP.NET Core backend with some Web APIs, and an AngularJS client on separate subdomains (Actually on localhost with different ports), and I can't seem to get Antiforgery to work.

I get **400 Bad request** response on APIs protected with [ValidateAntiForgeryToken], this is my backend code : 

```
services.AddAntiforgery(options => options.HeaderName = "X-XSRF-TOKEN");

...

app.Use(next => context => {
	tokens = antiforgery.GetAndStoreTokens(context);
	context.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions { HttpOnly = false });
	return next(context);
});
```

First problem i've got is that the cookie is not set on my AngularJS app, i've resolved it by setting WithCredentials to true :  `$httpProvider.defaults.withCredentials = true;`

The second one is that the X-XSRF-TOKEN header is not set automatically by AngularJS, and i've solved it by setting an interceptor :  `config.headers['X-XSRF-TOKEN'] = $cookies.get('XSRF-TOKEN');`

Now I can receive the token and send it with my $http requests, I don't understand why API calls are rejected ! Is it related that the applications are not on the same port ?

Thanks in advance :)

**Comment by Eilon** [comment] 2017-03-18 22:37
@kavinsky- perhaps it is the port. Can you try your browser's "debug" tool to see the network calls and whether the header and/or cookie are there? That'll probably tell us what's going on here.

**Comment by Eilon** [comment] 2017-03-22 21:19
@kavinsky- which server is creating the XSRF token, and which server is trying to check the XSRF token? They always need to be the same server. For example, the Angular app can't generate the token and then pass is to the Web API app. The app that generates the token has to be the one that accepts the token.

**Comment by Eilon** [comment] 2017-06-06 17:25
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-06-06 17:25 UTC
