### ISSUE TITLE
Antiforgery token works on remote not on localhost

### ISSUE THREAD

**Issue by nukec** [aspnet/Antiforgery#111] opened 2016-11-14 11:15 UTC
XSRF-TOKEN is not added on localhost in request headers.

Set-up in Startup.cs:
```
       public void ConfigureDevelopmentServices(IServiceCollection services)
        {
            services.AddAntiforgery(o => { o.HeaderName = "X-XSRF-TOKEN"; o.RequireSsl = false; });
            ConfigureEnvironmentAgnosticServices(services);
        }
```

Then in Configure method:
```
app.Use(next => context =>
            {
                if (
                    string.Equals(context.Request.Path.Value, "/", StringComparison.OrdinalIgnoreCase))
                {
                    var tokens = antiforgery.GetAndStoreTokens(context);
                    context.Items.Add("XSRF-TOKEN", tokens.RequestToken);
                }

                return next(context);
            });
```

Antiforgery middleware:
```
        public async Task Invoke(HttpContext context)
        {
            if (string.Equals(context.Request.Method, "POST", StringComparison.OrdinalIgnoreCase))
            {
                await _antiforgery.ValidateRequestAsync(context);
            }
            await _next.Invoke(context);
        }
```

Error:

> AntiforgeryValidationException: The required antiforgery header value "X-XSRF-TOKEN" is not present.

XSRF type is not added in headers in localhost, so it is impossible to test it on localhost. Works on remote servers though.

Can't seem to figure out this.

**Comment by Eilon** [comment] 2017-01-12 22:49
Hi, it's not clear to us what this code is trying to do. We don't see where the code is trying to send/receive the XSRF token. For example, the code that calls `context.Items.Add(...)` isn't sending the XSRF token to the client - it's just setting it in a data bag on the request.

Can you tell us more about what you are trying to achieve, and send a more complete code sample?

**Comment by Eilon** [comment] 2017-03-22 21:11
Closing because there is not enough info to reproduce this issue.

**Closed by Eilon** 2017-03-22 21:11 UTC
